### ISSUE TITLE
Changing Labels in Parameters

### ISSUE THREAD

**Issue by mbenjemaa** [skie/plum_search#19]
in documentation, it is mentioned that we can modify 'label':
       _formConfig: Contains Form::input $options settings like class, input type, label name..._

in my example, I have a field "ip_address". The label is shown automatically: "Ip Address". I wanted to put IP all in caps: "IP Address". So I put:
$parameters = [
             ['name' => 'ip_address', 'label' => 'IP Address', 'className' => 'Input'],

in another case:
$parameters = [
                ['name' => 'asset_status_id', 'className' => 'Select', 'label' => 'Status',

But did not work. Can you help please ?

**Comment by skie** [comment]
in controller you should define
```
        $inputOptions = [
            'search' => [
                'placeholder' => __('Type to search...'),
                'class' => 'form-control',
                'label' => 'Search'
            ]
        ];
        $this->set(compact('inputOptions'));
```

**Comment by mbenjemaa** [comment]
Thanks skie. Do you mean in <initialize> or in my <index> function inside controller ?

My initialize is a little bit complicated, like this and did understand where to put your code:

`       public function initialize()
        {
        parent::initialize();

        $parameters = [
            ['name' => 'serial_number', 'className' => 'Input'],
            ['name' => 'model_number', 'className' => 'Input'],
            ['name' => 'ip_address', 'label' => 'IP Address', 'className' => 'Input'],
        ];
        if ($this->request->param('action') == 'reportFacility') {
            $statuses = $this->AssetsAssignations->AssetStatuses->find('list')->order(['name' => 'asc']);
            $this->set(compact('asset_statuses'));
            $parameters = [
                ['name' => 'asset_status_id', 'className' => 'Select', 'label' => 'Status',
                    'finder' => $statuses
                ],
            ];
        }   elseif ($this->request->param('action') == 'reportClient') {
            $clients = $this->AssetsAssignations->Clients->find('list')->order(['last_name' => 'asc', 'first_name' => 'asc']);
            $this->set(compact('clients'));
            $parameters = [
                ['name' => 'client_id', 'className' => 'Select', 'label' => 'Client',
                    'finder' => $clients
                ],
            ];
        } elseif ($this->request->param('action') == 'reportRoom') {
            $rooms = $this->AssetsAssignations->Rooms->find('list')->order(['name' => 'asc']);
            $this->set(compact('rooms'));
            $parameters = [
                ['name' => 'room_id', 'className' => 'Select', 'label' => 'Room',
                    'finder' => $rooms
                ],
            ];
        }
        $this->loadComponent('PlumSearch.Filter', ['parameters' => $parameters]);
        
        
    }`

**Comment by skie** [comment]
Yes, you need it do it where you init search.
Look at search.ctp template code, it uses inputOptions to render elements defined by paramters.

```
$inputOptions = isset($inputOptions) ? $inputOptions : [];
$searchInputs = $this->Search->controls($searchParameters, $inputOptions);
```

**Comment by mbenjemaa** [comment]
Sorry, I did not find where exactly to put it in my code (I'm a beginner in Cakephp). Can you help please ?

**Comment by mbenjemaa** [comment]
found it:

`$parameters = [
    /* other fields here */
    [
        'name' => 'ip_address', 
        'className' => 'Input', 
        'formConfig' => ['label' => 'IP Address']
    ],
];
`
