### ISSUE TITLE
Tag New Version

### ISSUE THREAD

**Issue by amayer-hc** [skie/plum_search#25]
Would it be possible to get a new tag in the 4.x series to allow use with cakephp 4? The logic on the current tag can only be used if you are running cakephp version exactly "4.0.0", but the branch has [one additional commit](https://github.com/skie/plum_search/commit/471891e6a2a185729c9e1123f4f3148ea5e8620f) on it that fixes this issue. If you tagged 4.0.2 that would allow anyone using any version of cakephp 4.* to use this plugin.

**Comment by skie** [comment]
Done
