### ISSUE TITLE
Error: Call to a member function collection() on a non-object 

### ISSUE THREAD

**Issue by cruamps** [skie/plum_search#5]
SearchHelper always returns Fatal Error, when I follow _Quick sample_ of your Documentation. 

> Error: Call to a member function collection() on a non-object 
> File G:\wamp\www\ ... \vendor\skie\cakephp-search\src\View\Helper\SearchHelper.php 
> Line: 40

The controller loads Filter Component into _initialize()_ : 

``` php
    $this->loadComponent('PlumSearch.Filter', [
            'parameters' => [
                'name' => 'lastname' ,
                'className' => 'Input'
            ]
        ]);
```

And template calls SearchHelper : 

``` php
<?= $this->element('PlumSearch.search'); ?>
```

**Comment by cruamps** [comment]
This error appears only when we submit the search form.

**Comment by CakeDC** [comment]
Have you modified your index method like it is described?

```
public function index() {
    $this->set('users', $this->Paginator->paginate($this->Filter->prg($this->Users)));
}
```

**Comment by cruamps** [comment]
I used `$this->paginate()` instead of `$this->Paginator->paginate()` in my controller, but submitting search form always returns : 

> Error: Call to a member function collection() on a non-object
> File G:\wamp\www...\vendor\skie\cakephp-search\src\View\Helper\SearchHelper.php
> Line: 40

**Comment by cruamps** [comment]
This error cames from a useless instruction in my index method : 

``` php
$this->render('ContactManager.Contacts/index');
```

Without this line, submitting search seems to work.
